name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  SETUP_QEMU: false

  ENABLE_PUSH_IMAGE: ${{ vars.ENABLE_PUSH_IMAGE }}
  ENABLE_BUILD_IMAGE: ${{ vars.ENABLE_BUILD_IMAGE }}

  CI_BRANCH: ${{ vars.CI_BRANCH }}
  IMAGE_TAG: ${{ vars.IMAGE_TAG }}

  REGISTRY_URL: ghcr.io
  REGISTRY_USERNAME: ${{ github.actor }}
  REGISTRY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_NAME: ${{ github.repository }}

  # REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
  # REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
  # REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
  # IMAGE_NAME: ${{ vars.IMAGE_NAME }}

  DEPLOY_DISPATCH_TOKEN: ${{ secrets.DEPLOY_DISPATCH_TOKEN }}

  ENABLE_TRIGGER_DEPLOY: ${{ vars.ENABLE_TRIGGER_DEPLOY }}
  DEPLOY_OWNER: ${{ vars.DEPLOY_OWNER }}
  DEPLOY_REPOSITORY: ${{ vars.DEPLOY_REPOSITORY }}
  DEPLOY_WORKFLOW: ${{ vars.DEPLOY_WORKFLOW }}
  DEPLOY_BRANCH: ${{ vars.DEPLOY_BRANCH }}

jobs:
  image-build-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Set up QEMU
        if: ${{ env.SETUP_QEMU == 'true' }}
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Local build container image
        if: ${{ env.ENABLE_BUILD_IMAGE == 'true' }}
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: cr.ladesa.local/dev-docs
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Login into Registry
        if: ${{ env.ENABLE_PUSH_IMAGE == 'true' }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_TOKEN }}

      - name: Build and push container image to the registry
        if: ${{ env.ENABLE_PUSH_IMAGE == 'true' && env.ENABLE_BUILD_IMAGE == 'true' && github.ref_name == env.CI_BRANCH }}
        uses: docker/build-push-action@v6
        with:
          push: ${{ env.ENABLE_PUSH_IMAGE == 'true' }}
          tags: ${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Dispatch infrastructure deploy workflow
        if: ${{ env.ENABLE_BUILD_IMAGE == 'true' && env.ENABLE_PUSH_IMAGE == 'true' && env.ENABLE_TRIGGER_DEPLOY == 'true' }}
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ env.DEPLOY_DISPATCH_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ env.DEPLOY_OWNER }}/${{ env.DEPLOY_REPOSITORY }}/actions/workflows/${{ env.DEPLOY_WORKFLOW }}/dispatches \
            -d '{"ref":"${{ env.DEPLOY_BRANCH }}","inputs":{}}'
